
cLEDText ScrollingMsg;

const unsigned char TxtDemo[] = { EFFECT_FRAME_RATE "\x02"
                                  EFFECT_HSV_AV "\x00\xff\xff\x40\xff\xff"
                                  EFFECT_SCROLL_LEFT "        DRAGON*CON" 
                                  EFFECT_HSV_AV "\x00\xff\xff\x40\xff\xff"
                                  EFFECT_SCROLL_LEFT " DRAGON*CON"
                                  EFFECT_HSV_AV "\x00\xff\xff\x40\xff\xff"
                                  EFFECT_SCROLL_LEFT " DRAGON*CON"
                                  EFFECT_HSV_AV "\x00\xff\xff\x40\xff\xff"
                                  EFFECT_SCROLL_LEFT " DRAGON*CON"
                                  EFFECT_HSV_AV "\x00\xff\xff\x40\xff\xff"
                                  EFFECT_SCROLL_LEFT " DRAGON*CON"
                                  EFFECT_HSV_AV "\x00\xff\xff\x40\xff\xff"
                                  EFFECT_SCROLL_LEFT " DRAGON*CON"
                                  EFFECT_HSV_AV "\x00\xff\xff\x40\xff\xff"
                                  EFFECT_SCROLL_LEFT " DRAGON*CON"
                                  EFFECT_HSV_AV "\x00\xff\xff\x40\xff\xff"
                                  EFFECT_SCROLL_LEFT " DRAGON*CON"
                                  EFFECT_HSV_AV "\x00\xff\xff\x40\xff\xff"
                                  EFFECT_SCROLL_LEFT " DRAGON*CON"
                                  EFFECT_HSV_AV "\x00\xff\xff\x40\xff\xff"
                                  EFFECT_SCROLL_LEFT " DRAGON*CON"
                                  EFFECT_HSV_AV "\x00\xff\xff\x40\xff\xff"
                                  EFFECT_SCROLL_LEFT " DRAGON*CON"
                                  EFFECT_HSV_AV "\x00\xff\xff\x40\xff\xff"
                                  EFFECT_SCROLL_LEFT " DRAGON*CON"
                                  EFFECT_HSV_AV "\x00\xff\xff\x40\xff\xff"
                                  EFFECT_SCROLL_LEFT " DRAGON*CON"
                                  EFFECT_HSV_AV "\x00\xff\xff\x40\xff\xff"
                                  EFFECT_SCROLL_LEFT " DRAGON*CON"
                                  EFFECT_HSV_AV "\x00\xff\xff\x40\xff\xff"
                                  EFFECT_SCROLL_LEFT " DRAGON*CON"
                                  EFFECT_HSV_AV "\x00\xff\xff\x40\xff\xff"
                                  EFFECT_SCROLL_LEFT " DRAGON*CON"
                                  EFFECT_HSV_AV "\x00\xff\xff\x40\xff\xff"
                                  EFFECT_SCROLL_LEFT " DRAGON*CON"
                                  EFFECT_HSV_AV "\x00\xff\xff\x40\xff\xff"
                                  EFFECT_SCROLL_LEFT " DRAGON*CON"
                                  };
